export const CREATE_USER = "CREATE_USER"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAILED = "CREATE_USER_FAILED"

export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED"

export const NEW_POST = "NEW_POST"
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS"
export const NEW_POST_FAILED = "NEW_POST_FAILED"

export const INIT_USER = "INIT_USER"
export const INIT_USER_SUCCESS = "INIT_USER_SUCCESS"
export const INIT_USER_FAILED = "INIT_USER_FAILED"

export const FIND_USER = "FIND_USER"
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS"
export const FIND_USER_FAILED = "FIND_USER_FAILED"

export const ADD_USER_TO_LIST = "ADD_USER_TO_LIST"
export const ADD_USER_TO_LIST_SUCCESS = "ADD_USER_TO_LIST_SUCCESS"
export const ADD_USER_TO_LIST_FAILED = "ADD_USER_TO_LIST_FAILED"

